/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateBookDtoEbookInnerChaptersInner } from './create-book-dto-ebook-inner-chapters-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { UnfoldOutputImagesInner } from './unfold-output-images-inner';

/**
 * 
 * @export
 * @interface UnfoldOutput
 */
export interface UnfoldOutput {
    /**
     * 
     * @type {Array<CreateBookDtoEbookInnerChaptersInner>}
     * @memberof UnfoldOutput
     */
    'chapters': Array<CreateBookDtoEbookInnerChaptersInner>;
    /**
     * 
     * @type {Array<UnfoldOutputImagesInner>}
     * @memberof UnfoldOutput
     */
    'images': Array<UnfoldOutputImagesInner>;
}

